apiVersion: v1
kind: ServiceAccount
metadata:
  name: wi
  annotations:
    azure.workload.identity/client-id: cf71f997-0405-4951-95f5-5a2251d21e7e
---
apiVersion: v1
kind: Pod
metadata:
  name: azurecli-with-wi
  labels:
    azure.workload.identity/use: "true" # So admission control captures it
spec:
  serviceAccountName: wi
  containers:
  - args:
    - sleep
    - infinity
    image: mcr.microsoft.com/azure-cli
    name: azurecli
